language: generic
osx_image: xcode9.2
sudo: false
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - FASTLANE_LANE=ci_commit
matrix:
  include:
    - os: osx
      env: FASTLANE_LANE=code_coverage FASTLANE_ENV=default
    - os: osx
      env: FASTLANE_ENV=ios93
    - os: osx
      env: FASTLANE_ENV=tvos92
    - os: osx
      env: FASTLANE_ENV=osx
    - os: linux
      sudo: required
      dist: trusty
      env: SWIFT_VERSION=4.1
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./script/travis-install-linux; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./script/travis-install-macos; fi
script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./script/travis-script-linux; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./script/travis-script-macos; fi
after_success:
  - if [ "$FASTLANE_LANE" == "code_coverage" ]; then
     make post_coverage;
    fi
