language: objective-c
osx_image: xcode7.1
sudo: false
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - FASTLANE_LANE=ci_commit
matrix:
  include:
    - osx_image: xcode7.2
      env: FASTLANE_LANE=code_coverage FASTLANE_ENV=default
    - osx_image: xcode7.2
      env: FASTLANE_ENV=ios92
    - osx_image: xcode7.2
      env: FASTLANE_ENV=tvos91
    - osx_image: xcode7.2
      env: FASTLANE_ENV=osx
    - osx_image: xcode7.3
      env: FASTLANE_ENV=ios93_xcode73
before_install:
  - make install
script:
  - set -o pipefail
  - bundle exec fastlane $FASTLANE_LANE configuration:Debug --env $FASTLANE_ENV
  - bundle exec fastlane $FASTLANE_LANE configuration:Release --env $FASTLANE_ENV
after_success:
  - if [ "$FASTLANE_LANE" == "code_coverage" ]; then
     make post_coverage;
    fi
